name: Developer

on:
  push:
    branches:
      - '!release'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          scope: '@rango-team'
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Create .npmrc
        uses: ferluisxd/create-npmrc@3
        with:
          org_name: rango-team
        env:
          AUTH_TOKEN: ${{ secrets.RANGO_NPM_AUTH_TOKEN }}

      - name: Override "prepare" script
        run: npm set-script prepare ""

      - name: Install dependencies
        run: npm install --legacy-peer-deps --registry=https://registry.npmjs.org/

      - name: Cache the artifact
        uses: actions/cache@v3.0.8
        id: all
        with:
          path: ./*
          key: ${{ github.sha }}

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          scope: '@rango-team'
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Restore the cached files
        uses: actions/cache@v3.0.8
        id: all
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Test
        run: npm run test
