name: Production

on:
  push:
    branches:
      - release

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          scope: '@rango-team'
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Create .npmrc
        uses: ferluisxd/create-npmrc@3
        with:
          org_name: rango-team
        env:
          AUTH_TOKEN: ${{ secrets.RANGO_NPM_AUTH_TOKEN }}

      - name: Override "prepare" script
        run: npm set-script prepare ""

      - name: Generate package lock
        run: npm i --package-lock-only --legacy-peer-deps --registry=https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci --legacy-peer-deps --registry=https://registry.npmjs.org/

      - name: Cache the artifact
        uses: actions/cache@v3.0.8
        id: setup
        with:
          path: ./*
          key: ${{ github.sha }}

  code-health:
    name: Check code health
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          scope: '@rango-team'
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Restore the cached files
        uses: actions/cache@v3.0.8
        id: setup
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Check lint
        run: npm run check-lint

      - name: Check types
        run: npm run check-types

      - name: Check format
        run: npm run check-format

  test:
    name: Test
    needs: code-health
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          scope: '@rango-team'
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Restore the cached files
        uses: actions/cache@v3.0.8
        id: setup
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Test
        run: npm run test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          scope: '@rango-team'
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Restore the cached files
        uses: actions/cache@v3.0.8
        id: setup
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Build
        run: npm run build --if-present

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          scope: '@rango-team'
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Restore the cached files
        uses: actions/cache@v3.0.8
        id: setup
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
